- hosts: masters 
  become: true

  pre_tasks:
  - name: update all packages
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest

  - name: Install epel release
    yum:
      name: epel-release
      state: installed
      
  - name: Enable br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
    when: >
      ansible_distribution != 'Debian' 

  - name: ipforward to 1
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: disable swap
    shell: |
      swapon -a
    when: swap_disabled == true 
  - name: install ntp
    yum:
      name: ntp
      state: installed
  - name: update time
    service: name=ntpd state=restarted   

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.containerd
    - role: geerlingguy.kubernetes
      kubernetes_packages:
        - name: kubelet-{{ kubernetes_version_rhel_package }}
          state: present
        - name: kubectl-{{ kubernetes_version_rhel_package }}
          state: present
        - name: kubeadm-{{ kubernetes_version_rhel_package }}
          state: present
        - name: kubernetes-cni
          state: present

  post_tasks:
  - name: Configure Flannel networking for enp0s8
    shell: "curl {{ kubernetes_flannel_manifest_file }} | sed '/kube-subnet-mgr.*/a\\        - --iface=enp0s8' | kubectl apply -f -"
    register: flannel_result
    changed_when: "'created' in flannel_result.stdout"
    when: kubernetes_pod_network.cni == 'flannel' and installation_method == 'vagrant'
    retries: 3
    delay: 5
