all:
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#    ansible_python_interpreter: "/usr/bin/python3"
masters:
  hosts:
    master:
      ansible_host: 192.168.99.10 # A remplacer par l'IP de votre master
workers:      
  hosts:
    worker1:
      ansible_host: 192.168.99.11 # A remplacer par l'IP de votre worker1 
